#!/usr/bin/env bash
#
# load_backup.sh - Load teleport backup to system
#
# Usage:
#   load_backup.sh <backup> <user>@<ip>
#
# Description:
#   This program takes a backup generated by ./backup.sh and load
#   it on to a system with teleport.
#
# Author: Dan McCarthy
# Date: 3/13/2026

# check that ssh destination is provided
if [[ $# -ne 2 ]]; then
    echo "Please provide argument: './load_backup.sh <backup> <user>@<ip>'"
    exit 1
fi

BACKUP="$1"
TARGET="$2"

# === Copy local backup to system ===
read -p "Enter Password: " PASSWORD

echo "Sending backup to system..."
sshpass -p "$PASSWORD" scp $BACKUP "$TARGET:/tmp"

# === Extract backup ===
echo "Extracting backups on system..."
sshpass -p "$PASSWORD" ssh "$TARGET" sudo bash -s <<EOF

systemctl stop teleport

tar xzpf /tmp/$BACKUP -C / --same-owner

systemctl start teleport

EOF